"""Weekly AI tools + high-ticket sales research → Google Doc.

Runs Monday mornings before the 11am research block on aziza.muhammadx's
calendar fires. Each run creates a fresh Google Doc titled
"AI + High-Ticket Sales Research — Week of <Mon>".

Sources:
  - Hacker News (Algolia API) — past-week stories matching sales/AI/B2B keywords
  - Optional: extend with ProductHunt, Indie Hackers later

The script doesn't try to be a finished memo. It's a discovery feed —
5-10 candidate items per week, link + 1-line summary, ranked by HN
points (a rough proxy for "did people actually notice this?").

CLI:
    python -m reclaim.research generate   # build this week's doc
    python -m reclaim.research list       # show recent runs
"""
from __future__ import annotations

import argparse
import json
import sys
import urllib.parse
import urllib.request
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

from reclaim import google_docs


DEFAULT_TZ = ZoneInfo("America/Detroit")
SNAPSHOT_PATH = Path("config/research-snapshot.json")

HN_ALGOLIA = "https://hn.algolia.com/api/v1/search"

# Multi-pass search — each query returns top stories, we dedupe + score
QUERIES = [
    "AI sales",
    "B2B AI",
    "sales AI agent",
    "AI for sales",
    "GPT sales",
    "enterprise AI sales",
    "sales automation AI",
    "AI cold email",
]

# Score boosters — story is more relevant if its text matches these
RELEVANT_TERMS = [
    "enterprise", "B2B", "high-ticket", "upmarket",
    "outbound", "cold email", "sales rep", "SDR", "AE",
    "revenue", "ARR", "MRR", "deal", "pipeline",
    "agent", "automation", "augmented",
]

# Score penalties — these usually mean it's not what she's looking for
IRRELEVANT_TERMS = [
    "show hn", "ask hn",                # community posts, often noise
    "show off", "open source",           # often hobby projects
    "image generation", "stable diffusion",
    "voice clone", "deepfake",
]


def _fetch_hn(query: str, since_unix: int, max_hits: int = 20) -> list[dict]:
    """Return HN stories matching the query, posted after since_unix."""
    params = {
        "query": query,
        "tags": "story",
        "numericFilters": f"created_at_i>{since_unix}",
        "hitsPerPage": str(max_hits),
    }
    url = f"{HN_ALGOLIA}?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(
        url, headers={"User-Agent": "reclaim/0.1 (+https://github.com/azizaceo90/trackinng)"},
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read()).get("hits", [])


def _score(story: dict) -> int:
    """Higher score = more relevant. Combines HN points + keyword signals."""
    base = int(story.get("points") or 0)
    text = " ".join([
        story.get("title", "") or "",
        story.get("story_text", "") or "",
    ]).lower()
    for term in RELEVANT_TERMS:
        if term.lower() in text:
            base += 5
    for term in IRRELEVANT_TERMS:
        if term.lower() in text:
            base -= 20
    return base


def gather_candidates() -> list[dict]:
    """Run all queries, dedupe by URL, return top-ranked candidates."""
    since = int((datetime.now(timezone.utc) - timedelta(days=10)).timestamp())
    seen: dict[str, dict] = {}
    for q in QUERIES:
        try:
            hits = _fetch_hn(q, since)
        except Exception as ex:
            print(f"WARN: query {q!r} failed: {ex}", file=sys.stderr)
            continue
        for h in hits:
            url_key = h.get("url") or h.get("objectID")
            if not url_key or url_key in seen:
                continue
            h["_score"] = _score(h)
            h["_matched_query"] = q
            seen[url_key] = h
    out = list(seen.values())
    out.sort(key=lambda h: -h["_score"])
    # Drop low-confidence
    return [h for h in out if h["_score"] >= 5][:10]


def render_sections(candidates: list[dict], week_of: date) -> list[dict]:
    sections: list[dict] = []
    sections.append({"kind": "heading",
                     "text": f"AI + High-Ticket Sales Research — Week of {week_of:%b %d, %Y}"})
    sections.append({"kind": "paragraph",
                     "text": (
                         "Auto-generated by reclaim/research.py — pulled from Hacker News "
                         "stories matching AI / sales / B2B keywords over the past 10 days, "
                         "ranked by relevance score. Treat as a starting list; verify "
                         "anything before acting on it."
                     )})

    if not candidates:
        sections.append({"kind": "paragraph",
                         "text": "(No high-confidence candidates surfaced this week. "
                                 "Try widening QUERIES in reclaim/research.py.)"})
        return sections

    sections.append({"kind": "subheading", "text": "Top candidates"})
    for i, c in enumerate(candidates, 1):
        title = c.get("title", "(no title)").strip()
        url = c.get("url") or f"https://news.ycombinator.com/item?id={c.get('objectID')}"
        points = int(c.get("points") or 0)
        comments = int(c.get("num_comments") or 0)
        score = c.get("_score", 0)
        author = c.get("author") or "?"
        created = c.get("created_at", "")[:10]
        sections.append({
            "kind": "bullet",
            "text": (
                f"{title}\n"
                f"   {url}\n"
                f"   HN points: {points} · comments: {comments} · relevance score: {score} · "
                f"posted {created} by @{author} · matched query: {c.get('_matched_query')!r}"
            ),
        })

    sections.append({"kind": "subheading", "text": "Notes / next steps"})
    sections.append({"kind": "bullet", "text": "Which of these match the $25k–$100k upfront model?"})
    sections.append({"kind": "bullet", "text": "Any worth a 1-hour deep dive next week?"})
    sections.append({"kind": "bullet", "text": "What's the pricing / sales motion for the most interesting one?"})
    return sections


def generate() -> dict:
    """Run the weekly research pipeline. Returns metadata about the created doc."""
    token = google_docs.get_access_token("personal2")

    today = datetime.now(DEFAULT_TZ).date()
    # Monday of the current week
    monday = today - timedelta(days=today.weekday())
    title = f"AI + High-Ticket Sales Research — Week of {monday:%b %d, %Y}"

    candidates = gather_candidates()
    sections = render_sections(candidates, monday)

    doc = google_docs.create_doc(title, token)
    google_docs.write_doc(doc["doc_id"], sections, token)

    result = {
        "generated_at": datetime.now(DEFAULT_TZ).isoformat(),
        "week_of": monday.isoformat(),
        "title": title,
        "doc_url": doc["url"],
        "doc_id": doc["doc_id"],
        "candidate_count": len(candidates),
        "candidates_summary": [
            {"title": c.get("title", "")[:80], "score": c["_score"],
             "url": c.get("url", "")[:120]}
            for c in candidates
        ],
    }
    SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT_PATH.write_text(json.dumps(result, indent=2, default=str))
    return result


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(prog="reclaim.research")
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("generate", help="Build this week's research doc.")
    sub.add_parser("list", help="Show the most recent snapshot.")
    args = p.parse_args(argv)
    if args.cmd == "generate":
        r = generate()
        json.dump(r, sys.stdout, indent=2, default=str)
        sys.stdout.write("\n")
    elif args.cmd == "list":
        if SNAPSHOT_PATH.exists():
            print(SNAPSHOT_PATH.read_text())
        else:
            print("(no snapshot yet)")


if __name__ == "__main__":
    main()
